---
resources:
- name: grpc-gateway
  type: git
  source:
    branch: master
    uri: https://github.com/grpc-ecosystem/grpc-gateway.git

- name: things-source
  type: git
  source:
    branch: master
    uri: git@github.com:CoveredInsurance/example-things.git
    private_key: {{github-private-key}}

# - name: grpc-go-source
#   type: git
#   source:
#     branch: master
#     uri: https://github.com/grpc/grpc-go.git

jobs:
- name: unit-tests
  serial: true
  plan:
  - get: things-source
    trigger: true
  - task: run-unit-tests
    file: things-source/tasks/unit-tests.yml

- name: build-js
  serial: true
  plan:
  - aggregate:
    - get: things-source
      trigger: true
    - get: grpc-gateway
  - task: compile
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: node}
      inputs:
      - name: things-source
      - name: grpc-gateway
      outputs:
      - name: updated-things-source
      run:
        path: things-source/scripts/build_js.sh
  - put: things-source
    params: {repository: updated-things-source}

# - name: build-go
#   serial: true
#   plan:
#   - aggregate:
#     - get: things-source
#       trigger: true
#     - get: grpc-go-source
#   - task: compile
#     config:
#       platform: linux
#       image_resource:
#         type: docker-image
#         source: {repository: golang}
#       inputs:
#       - name: things-source
#       outputs:
#       - name: "src/github.com/CoveredInsurance/example-things"
#       run:
#         path: protoapi/scripts/build-go.sh
#   - put: things-source
#     params: {repository: "src/github.com/CoveredInsurance/example-things"}
